### ISSUE TITLE
Auto payout not working.

### ISSUE THREAD

**Issue by mjlamb** [NicolasDorier/boltcards-plugin#10]
I have been trying out the bolt card integration, and when i use the bolt card the payment is sitting "waiting approval" even thought I have it set in the factory "Automatically approve claims" and in the payout processor it to "Process approved payouts instantly" but still the payment sits awaiting approval.
Once I approve the payment in the btcpay server screen payment does complete, how do i make it automatic payout?

BTCPay Server v1.13.2

and the Plugin Extension = v1.1.2.0

**Comment by NicolasDorier** [comment]
it should be working. Do you see any error in the logs of BTCPay?

**Comment by mjlamb** [comment]
logs are very light, only seeing a few INFO entries, do i need to turn on debug level, how?

**Comment by mjlamb** [comment]
no error entries btw.

**Comment by NicolasDorier** [comment]
I just pushed a new version of the plugin (1.1.3) fixing a few things.

Can you try to:
* Update the plugin
* Go to your factory
* Click "Save"
* Try top-up again?

**Comment by mjlamb** [comment]
@NicolasDorier I have updated the plugin and it is working fine now, the sats arrived straight away on payment as expected.
Thanks
I noticed the automatic payment option checkbox is no longer available in the factory now fyi.

**Comment by NicolasDorier** [comment]
@mjlamb yeah, I removed the checkbox as there is no point in having it unchecked.
