### ISSUE TITLE
Resetting Boltcards: Auth Failed, code 91ae AUTHENTICATION_ERROR

### ISSUE THREAD

**Issue by petzsch** [NicolasDorier/boltcards-plugin#18]
Hi,

I think I just bricked a dozen boltcards. They are still linked to my store, but I can't reset them. Checking balance and paying still works. I just can't repurpose them.

Hope you have an idea. I'm on current Plugin (1.1.7.0) an BTCPay Version (2.0.2)

![boltcard_reset](https://github.com/user-attachments/assets/2060123c-7973-4cb8-8103-56dc5ab401b5)

**Comment by rockstardev** [comment]
@NicolasDorier this problem was identified in the end - https://github.com/boltcard/bolt-nfc-android-app/issues/45#issuecomment-2320403159  - but it was supposed to be fixed in the latest version of Bolt Card Programmer Android app.

**Comment by NicolasDorier** [comment]
@rockstardev unrelated, this is another problem.
