### ISSUE TITLE
How unique is the IssuerKey and will multiple IssuerKeys be allowed?

### ISSUE THREAD

**Issue by johnheenan** [NicolasDorier/boltcards-plugin#3]
I am using the terms IssuerKey as defined in https://github.com/boltcard/boltcard/blob/main/docs/DETERMINISTIC.md and as used by this extension.

Does each store get a unique IssuerKey or does each boltcard factory get its own IssuerKey?

The above document states in https://github.com/boltcard/boltcard/blob/main/docs/DETERMINISTIC.md#multiple-issuerkeys

> ### Multiple IssuerKeys
> A single LNUrl Withdraw Service can own multiple IssuerKeys. In such cases, it will need to attempt them all to decrypt p=, and pick the first one which satisfies PICCData[0] == 0xc7 and verifies the c= checksum.
> 
> Using multiple IssuerKeys can decrease the impact of a compromised Encryption Key (K1) at the cost of performance.

Is there a plan to allow use of multiple issuer keys, including self provided ones?

**Comment by johnheenan** [comment]
From https://github.com/btcpayserver/btcpayserver/blob/e5a09cbeaa48ce9fca258a7c3848ad5df0898bf8/BTCPayServer/Extensions/SettingsRepositoryExtensions.cs#L14
the issuer key is set once for the entire server.

So the IssuerKey is the same for all stores and for all botlcard factories.

**Comment by johnheenan** [comment]
> So the IssuerKey is the same for all stores and for all botlcard factories.

This poses an interesting question. 

Can a boltcard factory on a different store with different owner force a boltcard to be reset and reissued to their store if a user requests? 

My guess is yes. If true can safeguards be put in to ensure all fund are swept first?

Also, server wide use does not prevent server wide use of multiple IssuerKeys for the entire server.

**Comment by johnheenan** [comment]
> Can a boltcard factory on a different store with different owner force a boltcard to be reset and reissued to a factory in their store if a user requests?

I can see what happens myself when I receive NTAG 424 DNA NFC cards on order from KARUISI RFID Store,  https://www.aliexpress.com/item/1005005643502777.html

**Comment by johnheenan** [comment]
> I can see what happens myself when I receive NTAG 424 DNA NFC cards on order from KARUISI RFID Store, https://www.aliexpress.com/item/1005005643502777.html

The NFC cards from KARUISI RFID Store have been received. The cards are easily read by mobile phones at a distance exceeding one cm.

They cards are very inexpensive, the cheapest I have seen. They arrived reasonably quickly after a hold up for a few days at country of destination (Australia). I would advise anyone looking at getting cards to get at least 10 for a very simple reason: it is incredibly easy to make the cards non-functional.

I know the reason for the destroyed functionality, how to make it less likely to happen and how to make the cards functional again with an additional 'super recovery' feature that can be added in.

Payments can be made easily to Blink and Wallet of Satoshi wallets to top up their balance by withdrawing balance from the NFC cards, with a particular technique that works reliably. A POS feature is not required. The technique is not to let to phone to open a wallet app or to offer a choice of wallet apps to open, but to have the apps already primed to receive a top up with NFC 'pre activated', by tapping a button marked NFC on a receive page, after entering an amount.

The cards can have a 'balance' topped up at well over a claim limit, as illustrated in image below! A negative 'Already Claimed' amount means more has been put back in to top up the card than has been withdrawn.

![image](https://github.com/NicolasDorier/boltcards-plugin/assets/22131790/f02fd445-3c5f-4638-bc2a-ebd6ca461e24)

I don't want to comment any more until I have more experience, including about issues I have already raised.

**Comment by johnheenan** [comment]
**What having a single boltcard IssuerKey for an entire server means in practice:**

I set up the same boltcard on the same BTCPay server on different stores with no common ownership.

1. I was able to reset a boltcard with an unswept balance from one store (the first) on another store (the second).
2. I was able to use a factory on the second store to set up a new boltcard to use the lightning account of the second store instead.
3. I was able to withdraw funds from the second store
4. I reset the boltcard again on the first store
5. I used the same factory again on the first store as I originally did however the card became non functional. I don't know why yet.

**Comment by NicolasDorier** [comment]
> The cards can have a 'balance' topped up at well over a claim limit, as illustrated in image below! A negative 'Already Claimed' amount means more has been put back in to top up the card than has been withdrawn.

This is normal, the top-up is a hack on top of pull payments. They are effectively a negative payout.

**Comment by NicolasDorier** [comment]
> I was able to reset a boltcard with an unswept balance from one store (the first) on another store (the second).

In 1.1.15 I may have fixed your main issue: https://github.com/NicolasDorier/boltcards-plugin/commit/be23b24c0e7721ea42409e3be25cc8e05cedde3c

> I used the same factory again on the first store as I originally did however the card became non functional. I don't know why yet.

Should be fixed by https://github.com/NicolasDorier/boltcards-plugin/commit/537452c5299165ded69d37b73cc1cc9a8446d60d

I am closing your issues as it is difficult to follow what else need to be done. Please open a different issue with what is missing.
