### ISSUE TITLE
Requesting confirmation the last-seen counter is checked before a pull payment is approved with boltcard on BTCPay Server

### ISSUE THREAD

**Issue by johnheenan** [NicolasDorier/boltcards-plugin#4]
Suppose an NFC reader is used to scan a boltcard but the scanned lnurlw is retained with the internal counter set to 100, without lnurlw used to make a payment.

Suppose another scan is attempted with internal counter set to 101 and results in a successful payment.

Suppose the retained lnurlw is used afterwards with encrypted counter set to 100 to withdraw funds.

Will this pull payment request be automatically rejected by BTCPay Server because it recorded and so checked the last-seen counter?

**Comment by johnheenan** [comment]
I know the answer is obvious. 

But we need the emperor of BTCPayServer to state this is so, so us plebs can sound convincing.

**Comment by johnheenan** [comment]
The answer is yes. If a boltcard is successfully used after an unused scan of a lnurlw from a boltcard then that retained lnurlw is useless.

This means a scanned but unused lnurlw becomes useless if even 1 SAT is subsequently withdrawn.

I proved this with a BTCPay Server boltcard, the NFC Tools app on a mobile and the blink app on the same mobile. 

With blink, funds are received from a boltcard NFC scan through receive but if a pre-scanned raw lnurlw from a boltcard is used then pasting into the send box is used instead. End result is the same: funds are received if the lnurlw is still valid.

1. Scan a lnurlw with NFC Tools and copy it into clipboard, paste it into send box (not receive) of blink app and receive funds.
2. Repeat scan again of lnurlw from boltcard in NFCTools app but this time receive funds through blink app first with another scan through receive (not send) and tap of NFC button in the blink app.
3. Paste the retained lnurlw from the clipboard into send box of blink. Receive of funds fails with a message of 'Please enter a valid destination'.

I will leave this issue open for while in case anyone want to comment.

**Comment by NicolasDorier** [comment]
So as you have seen, the answer is yes, it will be rejected. This is on design, when a withdraw is made the counter need to be up to prevent "double spending".
