### ISSUE TITLE
Requesting a boltcard reset determine the real version number of a boltcard before reset and that VERSION mismatches be managed

### ISSUE THREAD

**Issue by johnheenan** [NicolasDorier/boltcards-plugin#6]
I recently received 20 blank boltacrds from KARUISI RFID Store, https://www.aliexpress.com/item/1005005643502777.html

So far I have set up five of them. Currently four of the cards are useless. While all four show a balance when scanned with the BTCPay Server on a mobile, I cannot withdraw from them and they all show a 91AE authentication error message when attempting to be reset with the Boltcard NFC Programmer app.

Using blink with NFC receive fails but does not give an error message. However, if I read the lnurlw with NFC Tools and paste the lnurlw into blink send instead, then I get error message 'Please enter a valid destination', the same as when a stale lnurlw is used, as reported at https://github.com/NicolasDorier/boltcards-plugin/issues/4#issuecomment-2168649282. Also, this link reports on circumstances that led to one card becoming unusable. The technique of using send for a raw lnurlw and read for an NFC card is valid in blink and is mentioned in the link.

On BTCPay Server, a boltcards five programmed app keys are uniquely determined by three records, the server IssuerKey, the UID of the card and the recorded VERSION of the card. Since the IssuerKey and the UID don't change, my guess is that the cause of the problem is that the recorded VERSION has advanced while the new keys for a boltcard of that VERSION failed to get reprogrammed in.

It is very easy to solve this problem. When resetting, check if there is a version mismatch instead of assuming the boltcard got reset with the keys for the VERSION on record by counting back down versions (to a limit) until there is a match.

Using https://github.com/boltcard/boltcard/blob/main/docs/DETERMINISTIC.md, the K1 key is not version dependent but the K2 key is and it is used as the authentication key for the c parameter. Hence the algorithm to determine the real VERSION of the keys is simple and quick.

The new state (Reset) and VERSION of the boltcard can still match the recorded VERSION instead of the previous real VERSION of the boltcard (which the boltcard has itself has no internal record of).

**So, I am requesting during reset a check is done to determine the real VERSION used by the boltcard keys and to offer these keys for reset.**

**Also, I am requesting a feature is offered to allow a scan to be used to let users know if there is a VERSION mismatch and to allow an appropriate correction to be made, either by resetting the VERSION on record or requiring a boltcard be reset and reprogrammed with the keys for another VERSION of keys.**

**Comment by johnheenan** [comment]
The practice of BTCPay Server of incrementing VERSION in server records without confirming the card has been successfully re-programmed with the five new app keys is a BUG, using the definition of VERSION from https://github.com/boltcard/boltcard/blob/main/docs/DETERMINISTIC.md

Definition:
> Version: A 4-bytes little endian version number. This must be incremented every time the user re-programs (reset/setup) the same BoltCard on the same LNUrl Withdraw Service

Whether the bug lies with BTCPay Server or with the document or is shared is immaterial to users, such as myself and others. I now have four unusable cards and I don't care whose fault it is. I want them FIXED! I can add in programming myself to fix the cards, but this is an unreasonable expected action at my user level. Example of how a card became unusable at https://github.com/NicolasDorier/boltcards-plugin/issues/4#issuecomment-2168649282, however it is trivial to make any card unusable with another reset attempt without the previous having succeeded and being confirmed.

The document only recognises two states for a boltcard. 'Reset' and 'Configured'. BTCPay Server needs to recognise a third state with name such as ' PendingReset', with a record of what the old version number is and what the new version number is. I will raise a new issue on the github for the document and add a link here as an additional comment.

I used the term VERSION loosely above, but the intent is clear. The VERSION is not an inherent property of the card or any programming techniques. It is purely an administrative record and must be treated only as such, with all of the processes that are expected with an administrative workflow, including confirmation and correction.

BTCPay Server should record BOTH the newly attempted VERSION and the last successfully verified VERSION with a card state of 'PendingReset'. BTCPay Server can record a change of card state from 'PendingReset' to 'Reset' or 'Configured' with a later scan.

The precise technique of confirmation does not to be fully specified by the document. It is an implementation issue, such as by BTCPay Server.

A subsequently reset card with its offered UID can be confirmed as a reset card if it can be reprogrammed as if it is reset, thus offering safety.

**Comment by johnheenan** [comment]
Document authors notified at https://github.com/boltcard/boltcard/issues/80#issue-2354607722

**Comment by NicolasDorier** [comment]
Note that our implementation also use the PullPaymentId as part of the key. But I will check if I can't try to brute force the version.

**Comment by NicolasDorier** [comment]
I think my new commit will make it more reliable!

**Comment by NicolasDorier** [comment]
I release a new version 1.1.4 of the plugin. Let me know if it allows you to reset your cards. Re-open if not. (also close https://github.com/boltcard/boltcard/issues/80 as it isn't a problem of specification.)

**Comment by NicolasDorier** [comment]
Actually my "fix" doesn't work, because we don't keep track of previous pull payments and so we can't generate the same keys as the previous Setup.

**Comment by johnheenan** [comment]
So why not add in what the last known successfully used pull payment ID as a safeguard in an extra field?

**Comment by johnheenan** [comment]
How about the following that would stop cards from being bricked and also act as a proxy for a card state of confirmed or of unconfirmed.

The existing ppid column in the boltcard table is either set with a single pull payment id or is null. No change to existing code intentions. Only change the interpretation. Null meaning card is supposed to be reset, confirmed or not. Set meaning card is supposed to use the set ppid for current keys, confirmed or not.

An additional json column  is added to the boltcard table that is for a json array of ppids, say called the ppid_attempted column.

Every time there is an attempt to either reset a card from a supposed set state or set a card from a supposed reset state then the ppid used for the attempt is added to the ppid_attempted json array.

Once there is a confirmation that a card has been reset or or has been set with the value in the ppid column then clear the ppid_attempted column to null or an empty array.

**This is the proxy for my proposed card state:**
ppid refers to existing column in boltcard table and ppid_attempted refers to a new proposed json column in boltcard table

**confirmed reset**: ppid is null and ppid_attempted is null or an empty array
**confirmed set** ppid is not null and ppid_attempted is null or an empty array
**unconfirmed reset**: ppid is null and ppid_attempted contains a non empty array of at least one entry
**unconfirmed set** ppid is not null and ppid_attempted contains a non empty array of at least one entry

**Comment by johnheenan** [comment]
I should also add that the proposed ppid_attempted column value can also be used to note if there is a duplicate attempt to try set keys  again with a particular ppid. Perhaps a record of attempts to use a particular ppid should be included.

**Comment by johnheenan** [comment]
In addition, the last type of action with a particular ppid can be recorded, such as an attempt to reset or an attempt to set. Hence a particular set of ppid array records in the ppid_attempted column might be
```
[
"ppid1" : {attempts: 1, last_action: "reset"},
"ppid2" : {attempts: 2, last_action: "set"},
]
```

**Comment by johnheenan** [comment]
It might be argued that the approach above does not necessarily include the last confirmed ppid in ppid_attempted array column. I mentioned this as a suggestion to save before mentioning the ppid_attempted array column. 

However if was not included in the ppid_attempted array then this is a software fault because the only justifcation for using a particular ppid to attempt a reset of an already set car is if was already a confirmed ppid.

**Comment by johnheenan** [comment]
Some corrections and adding record of card version.

Another record worth considering recording in proposed ppid_attempted record is the version number used to generate a particular set of keys. It should always be less than or equal to the current version number in the boltcard table record.

First, the previous example provided was not valid json for recording within ppid_attempted. Below are two ways of recording attempts as valid json that you can test yourself by copying and pasting as heredocs through jq in a bash shell.

Recovery could be speeded up by recording within a ppid record the min and max version values used. First example below is not a json array. It is a json object that can easily be serialised/deserialised from/to a native instance object:

```
cat << EOL | jq
{
  "ppid1":
  {
    "attempted_resets": 1,
    "attempted_sets":   0,
    "first_attempted_action": "reset",
    "last_attempted_action":  "reset",
    "first_attempt_timestamp": 1720339534,
    "last_attempt_timestamp":  1720339534,
    "version_min": 3,
    "version_max": 3
  },
  "ppid2": 
  {
    "attempted_resets": 0,
    "attempted_sets":   2,
    "first_attempted_action": "set",
    "last_attempted_action":  "set",
    "first_attempt_timestamp": 1720339634,
    "last_attempt_timestamp":  1720339734,
    "version_min": 4,
    "version_max": 5
  }
}
EOL
```

If a recovery action does not use the correct version number for the keys then recovery will fail. So several attempts may be required. 

An alternative is to record every single version used for every single attempt. This second example below is a json array of json objects. Again, it can easily be serialised/deserialised from/to a native instance array of objects:

```
cat << EOL | jq
[
  {
    "ppid": "ppid1",
    "version": 3,
    "attempted_action":  "reset",
    "attempt_timestamp": 1720339534
  },
  {
    "ppid": "ppid2",
    "version": 4,
    "attempted_action":  "set",
    "attempt_timestamp": 1720339634
  },
  {
    "ppid": "ppid2",
    "version": 5,
    "attempted_action":  "set",
    "attempt_timestamp": 1720339734
  }
]
EOL
```

The advantage of the first approach is a better overall view from immediate inspection of database records. Its disadvantage is a potential partial loss of information of which version was used for any attempt (so perhaps requiring more recovery attempts).

The advantage of the second approach is full knowledge of how to generate keys for any particular attempt. Its disadvantage is a lack of the overall view of the first approach from an inspection of database records. However the records of the second approach can be easily processed to make them look like the records of the first approach.
