### ISSUE TITLE
scanning boltcards factory QR results in unexpexted token in boltcard creator app

### ISSUE THREAD

**Issue by warioishere** [NicolasDorier/boltcards-plugin#8]
As the title says, scanning the QR on a Bolt Card Factory on btcpay server, I get a `Error: JSON Parse Error: unexpected token` in boltcard creator app.

nginx logs in the moment of scanning the QR:

```
btcpay.yourdevice.ch 172.16.1.9 - - [28/Jun/2024:21:13:05 +0000] "GET /apps/xxxx/boltcardfactory HTTP/1.1" 200 3922 "-" "okhttp/4.9.2"
```

steps to reproduce: created a new store and a new factory, same error.

Steps to make it work:

Scan QR with a Camera App on Android and open the link. the btcpay Program Boltcard setup appears. When pressing on Setup, the boltcard creator app opens and sucessfully registers the store .

Greetings

**Comment by NicolasDorier** [comment]
@warioishere do I understand properly that this error `Error: JSON Parse Error: unexpected token` happens after you click on `Setup` button?

**Comment by warioishere** [comment]
> @warioishere do I understand properly that this error `Error: JSON Parse Error: unexpected token` happens after you click on `Setup` button?

No, after I directly scan the QR code shown in the factory, with boltz card creator app.

**Comment by NicolasDorier** [comment]
The QR code that you scan shown in the factory when you open the page on your laptop/desktop isn't meant to be scanned from the boltz card creator. It is meant to be scanned by a normal QR reader. The QR code is nothing but a link to a web page which allow you to either reset or register a new card.

**Comment by NicolasDorier** [comment]
I have pushed a commit clarifying the instructions.

**Comment by warioishere** [comment]
aaah sorry shit, yea, I found the way its intented to be used correctly out myself then. 
Thats what I did afterwards, scan the QR with a normal scanner, open the link, press setup, then boltcard creator App opens correctly. 

Thanks for clarifying for new users in future.
