### ISSUE TITLE
Clean up UI

### ISSUE THREAD

**Issue by ndeet** [NicolasDorier/boltcards-plugin#9]
As discussed in prague we could remove some options as they will be always the same:
- currency dropdown fixed to "SATS"
- "automatically approve claims" should be auto-checked and maybe not shown at all
- "payment methods" selection should be only BTC (Off-chain) too? no need to show other options?

**Comment by NicolasDorier** [comment]
I have:

* Replace Currency free entry by a dropdown only allowing BTC and SATS
* Removed `automatically approve claims`, making it always true
* Kept payment methods, but making them all selected by default. When we give access to pull payments, we want users to be able to withdraw on-chain for example.

**Comment by ndeet** [comment]
Makes sense, thanks!
